package tests.logic.player;

import dnd.logic.Tick;
import dnd.logic.player.Mage;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MageTest {
    MageMock mage;

    @BeforeEach
    void setUp() {
        mage = new MageMock("Test Mage", 100, 10, 5, 20, 50,30, 3, 4);
    }

    @AfterEach
    void tearDown() {
    }

    @Test
    void onTick_manaRegenerated() {
        mage.setCurrentMana(40);
        mage.onTick(new Tick(0));
        Assertions.assertEquals(mage.getCurrentMana(), 41, "mana should have regenerated by 1 from 40 to 41");
    }

    @Test
    void onTick_manaNotSurpassingManaPool() {
        mage.setCurrentMana(50);
        mage.onTick(new Tick(0));
        Assertions.assertEquals(mage.getCurrentMana(), 50, "current mana should have not surpassed 50");
    }
}